### ISSUE TITLE
Configuration interfactively

### ISSUE THREAD

**Issue by a-suenami** [mi2zq/senju#10]
I want to make `~/.senju` by senju command.

**Comment by myun2** [comment]
Does that mean that you want to create a configuration file interactively?

**Comment by a-suenami** [comment]
Both interactive and non-interactive is OK.
My essential issue is to run `mkdir` (or other Unix native commands) to start using senju.
All to start senju should be provided by senju.

**Comment by myun2** [comment]
like `$ senju add github`.

**Comment by myun2** [comment]
It's ready for Projects settings. https://github.com/mi2zq/senju/commit/519377caadbe8f51122cb77817b60c3a8c2667db https://github.com/mi2zq/senju/commit/34f263c3015ad804001de6e437834aeff5e501d5
